// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA09g1KwIt-Mylg7sk4O--nGen-9MhfJ-4',
    appId: '1:455265051902:android:48c3c6c31a093ed3eab1af',
    messagingSenderId: '455265051902',
    projectId: 'flutter-practice-41b2e',
    databaseURL: 'https://flutter-practice-41b2e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practice-41b2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLkVblKjJdAZhZ4YtjCsVaodSJ3Vu0Us',
    appId: '1:455265051902:ios:1262e213770e4775eab1af',
    messagingSenderId: '455265051902',
    projectId: 'flutter-practice-41b2e',
    databaseURL: 'https://flutter-practice-41b2e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-practice-41b2e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
